# Generated by Django 5.2 on 2025-04-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='consecutive_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='current_interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='easiness_factor',
            field=models.FloatField(default=2.5),
        ),
    ]
