# Generated by Django 5.2 on 2025-04-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_card_last_reviewed_card_times_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='next_review_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ] 