# Generated by Django 5.2 on 2025-04-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='personas',
            field=models.ManyToManyField(blank=True, related_name='decks', to='users.persona'),
        ),
    ]
