# Generated by Django 5.2 on 2025-04-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_deck_personas'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
